// MIT (Massachusetts Institute of Technology) Academic Student Life Cycle Master Data
// Incorporates MIT Course Departments, General Institute Requirements (GIR), 5.0 GPA Standards, UAC Advising, UROP and CAP Review

export const MIT_SAMPLE_DATA = {
  "Programme": [
    {
      "id": "prog-mit-course6-3",
      "code": "Course 6-3",
      "name": "Computer Science and Engineering",
      "degree_type": "bachelors",
      "degree_title": "S.B. in Computer Science and Engineering",
      "faculty": "School of Engineering",
      "department": "Electrical Engineering and Computer Science (EECS)",
      "duration_value": 4,
      "duration_unit": "years",
      "total_credits": 180,
      "credits_per_year": 45,
      "pass_mark": 50,
      "distinction_mark": 80,
      "status": "active",
      "max_capacity": 450
    },
    {
      "id": "prog-mit-course18",
      "code": "Course 18",
      "name": "Mathematics",
      "degree_type": "bachelors",
      "degree_title": "S.B. in Mathematics",
      "faculty": "School of Science",
      "department": "Department of Mathematics",
      "duration_value": 4,
      "duration_unit": "years",
      "total_credits": 180,
      "credits_per_year": 45,
      "pass_mark": 50,
      "distinction_mark": 80,
      "status": "active",
      "max_capacity": 200
    },
    {
      "id": "prog-mit-course8",
      "code": "Course 8",
      "name": "Physics",
      "degree_type": "bachelors",
      "degree_title": "S.B. in Physics",
      "faculty": "School of Science",
      "department": "Department of Physics",
      "duration_value": 4,
      "duration_unit": "years",
      "total_credits": 180,
      "credits_per_year": 45,
      "pass_mark": 50,
      "distinction_mark": 80,
      "status": "active",
      "max_capacity": 150
    },
    {
      "id": "prog-mit-course2",
      "code": "Course 2",
      "name": "Mechanical Engineering",
      "degree_type": "bachelors",
      "degree_title": "S.B. in Mechanical Engineering",
      "faculty": "School of Engineering",
      "department": "Department of Mechanical Engineering",
      "duration_value": 4,
      "duration_unit": "years",
      "total_credits": 180,
      "credits_per_year": 45,
      "pass_mark": 50,
      "distinction_mark": 80,
      "status": "active",
      "max_capacity": 250
    },
    {
      "id": "prog-mit-course15",
      "code": "Course 15-1",
      "name": "Management",
      "degree_type": "bachelors",
      "degree_title": "S.B. in Management",
      "faculty": "Sloan School of Management",
      "department": "Sloan Undergraduate Education",
      "duration_value": 4,
      "duration_unit": "years",
      "total_credits": 180,
      "credits_per_year": 45,
      "pass_mark": 50,
      "distinction_mark": 80,
      "status": "active",
      "max_capacity": 180
    }
  ],
  "Course": [
    {
      "id": "crs-18-01",
      "code": "18.01",
      "name": "Calculus I (Single Variable)",
      "credits": 12,
      "units": 12,
      "gir_category": "Science Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-18-02",
      "code": "18.02",
      "name": "Calculus II (Multivariable)",
      "credits": 12,
      "units": 12,
      "gir_category": "Science Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-8-01",
      "code": "8.01",
      "name": "Physics I: Classical Mechanics",
      "credits": 12,
      "units": 12,
      "gir_category": "Science Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-8-02",
      "code": "8.02",
      "name": "Physics II: Electricity & Magnetism",
      "credits": 12,
      "units": 12,
      "gir_category": "Science Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-5-111",
      "code": "5.111",
      "name": "Principles of Chemical Science",
      "credits": 12,
      "units": 12,
      "gir_category": "Science Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-7-012",
      "code": "7.012",
      "name": "Introductory Biology",
      "credits": 12,
      "units": 12,
      "gir_category": "Science Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-21w-755",
      "code": "21W.755",
      "name": "Writing and Reading the Essay (CI-H)",
      "credits": 12,
      "units": 12,
      "gir_category": "HASS / CI-H",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 70,
      "exam_weight": 30
    },
    {
      "id": "crs-21m-011",
      "code": "21M.011",
      "name": "Introduction to Western Music (HASS-A)",
      "credits": 12,
      "units": 12,
      "gir_category": "HASS-A",
      "type": "elective",
      "status": "active",
      "coursework_weight": 50,
      "exam_weight": 50
    },
    {
      "id": "crs-14-01",
      "code": "14.01",
      "name": "Principles of Microeconomics (HASS-S)",
      "credits": 12,
      "units": 12,
      "gir_category": "HASS-S",
      "type": "elective",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-6-0001",
      "code": "6.0001",
      "name": "Intro to CS & Programming in Python (REST)",
      "credits": 12,
      "units": 12,
      "gir_category": "REST",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 50,
      "exam_weight": 50
    },
    {
      "id": "crs-6-006",
      "code": "6.006",
      "name": "Introduction to Algorithms",
      "credits": 12,
      "units": 12,
      "gir_category": "Major Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 45,
      "exam_weight": 55
    },
    {
      "id": "crs-6-004",
      "code": "6.004",
      "name": "Computation Structures",
      "credits": 12,
      "units": 12,
      "gir_category": "Major Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 50,
      "exam_weight": 50
    },
    {
      "id": "crs-6-036",
      "code": "6.036",
      "name": "Introduction to Machine Learning",
      "credits": 12,
      "units": 12,
      "gir_category": "Major Elective",
      "type": "elective",
      "status": "active",
      "coursework_weight": 50,
      "exam_weight": 50
    },
    {
      "id": "crs-6-033",
      "code": "6.033",
      "name": "Computer System Engineering (CI-M)",
      "credits": 12,
      "units": 12,
      "gir_category": "CI-M",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 60,
      "exam_weight": 40
    },
    {
      "id": "crs-6-115",
      "code": "6.115",
      "name": "Microcomputer Project Laboratory (Lab)",
      "credits": 12,
      "units": 12,
      "gir_category": "Institute Lab",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 80,
      "exam_weight": 20
    },
    {
      "id": "crs-18-03",
      "code": "18.03",
      "name": "Differential Equations (REST)",
      "credits": 12,
      "units": 12,
      "gir_category": "REST",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    },
    {
      "id": "crs-18-06",
      "code": "18.06",
      "name": "Linear Algebra",
      "credits": 12,
      "units": 12,
      "gir_category": "Major Core",
      "type": "compulsory",
      "status": "active",
      "coursework_weight": 40,
      "exam_weight": 60
    }
  ],
  "Student": [
    {
      "id": "student-mit-01",
      "student_number": "928410293",
      "mit_id": "928410293",
      "kerberos_id": "priyar",
      "first_name": "Priya",
      "last_name": "Ramanathan",
      "email": "priyar@mit.edu",
      "phone": "+1 (617) 253-1001",
      "gender": "female",
      "cohort_year": "2026",
      "class_year": "Class of 2030",
      "current_year": 1,
      "current_semester": "semester_1",
      "academic_stage": "first_year_fall",
      "stage_label": "Phase 2: First-Year Fall (Pass/No Record)",
      "programme_id": null,
      "programme_name": "First-Year (Undeclared / Course 0)",
      "declared_major": null,
      "first_year_advisor": "Prof. Gerald Sussman",
      "associate_advisor": "Alex Chen '27",
      "uac_seminar": "SP.210 - The Joy of Engineering",
      "grading_policy": "first_year_fall",
      "cap_standing": "good_standing",
      "cap_status_label": "Good Standing (P/NR Protected)",
      "cumulative_gpa": 5.0,
      "term_rating": 5.0,
      "total_units_passed": 48,
      "total_credits_earned": 48,
      "pe_points_completed": 2,
      "swim_test_passed": true,
      "status": "enrolled",
      "fees_status": "paid",
      "outstanding_balance": 0,
      "urop_active": false
    },
    {
      "id": "student-mit-02",
      "student_number": "928391024",
      "mit_id": "928391024",
      "kerberos_id": "mvance",
      "first_name": "Marcus",
      "last_name": "Vance",
      "email": "mvance@mit.edu",
      "phone": "+1 (617) 253-1002",
      "gender": "male",
      "cohort_year": "2025",
      "class_year": "Class of 2029",
      "current_year": 1,
      "current_semester": "semester_2",
      "academic_stage": "first_year_spring",
      "stage_label": "Phase 3: First-Year Spring (Major Declaration Pending)",
      "programme_id": "prog-mit-course6-3",
      "programme_name": "First-Year (Declaring Course 6-3 EECS)",
      "declared_major": "Course 6-3: Computer Science & Engineering",
      "first_year_advisor": "Prof. Gerald Sussman",
      "departmental_advisor": "Prof. Shafi Goldwasser",
      "grading_policy": "first_year_spring",
      "cap_standing": "good_standing",
      "cap_status_label": "Good Standing",
      "cumulative_gpa": 4.75,
      "term_rating": 4.8,
      "total_units_passed": 96,
      "total_credits_earned": 96,
      "pe_points_completed": 4,
      "swim_test_passed": true,
      "status": "enrolled",
      "fees_status": "paid",
      "outstanding_balance": 0,
      "urop_active": true,
      "urop_title": "Distributed Byzantine Fault Tolerance at CSAIL"
    },
    {
      "id": "student-mit-03",
      "student_number": "928184912",
      "mit_id": "928184912",
      "kerberos_id": "skowal",
      "first_name": "Sophia",
      "last_name": "Kowalski",
      "email": "skowal@mit.edu",
      "phone": "+1 (617) 253-1003",
      "gender": "female",
      "cohort_year": "2024",
      "class_year": "Class of 2028",
      "current_year": 2,
      "current_semester": "semester_1",
      "academic_stage": "sophomore_major",
      "stage_label": "Phase 4: Course 6-3 Major & CSAIL UROP",
      "programme_id": "prog-mit-course6-3",
      "programme_name": "Course 6-3: Computer Science and Engineering",
      "declared_major": "Course 6-3: Computer Science and Engineering",
      "declared_minor": "Course 18: Mathematics",
      "departmental_advisor": "Prof. Shafi Goldwasser",
      "grading_policy": "regular",
      "cap_standing": "dean_list",
      "cap_status_label": "Dean's List / High Standing (4.92 / 5.0)",
      "cumulative_gpa": 4.92,
      "term_rating": 5.0,
      "total_units_passed": 144,
      "total_credits_earned": 144,
      "pe_points_completed": 6,
      "swim_test_passed": true,
      "status": "enrolled",
      "fees_status": "paid",
      "outstanding_balance": 0,
      "urop_active": true,
      "urop_title": "Zero-Knowledge Cryptographic SNARKs for Decentralized Ledgers"
    },
    {
      "id": "student-mit-04",
      "student_number": "928091823",
      "mit_id": "928091823",
      "kerberos_id": "dkim27",
      "first_name": "David",
      "last_name": "Kim",
      "email": "dkim27@mit.edu",
      "phone": "+1 (617) 253-1004",
      "gender": "male",
      "cohort_year": "2023",
      "class_year": "Class of 2027",
      "current_year": 3,
      "current_semester": "semester_2",
      "academic_stage": "junior_iap_urop",
      "stage_label": "Phase 4: Junior Term & IAP Robotics Challenge",
      "programme_id": "prog-mit-course2",
      "programme_name": "Course 2: Mechanical Engineering",
      "declared_major": "Course 2: Mechanical Engineering",
      "departmental_advisor": "Prof. Robert Langer",
      "grading_policy": "regular",
      "cap_standing": "good_standing",
      "cap_status_label": "Good Standing",
      "cumulative_gpa": 3.78,
      "term_rating": 3.85,
      "total_units_passed": 240,
      "total_credits_earned": 240,
      "pe_points_completed": 8,
      "swim_test_passed": true,
      "status": "enrolled",
      "fees_status": "paid",
      "outstanding_balance": 0,
      "urop_active": true,
      "urop_title": "Biomimetic Soft Actuators at MIT Media Lab"
    },
    {
      "id": "student-mit-05",
      "student_number": "927891002",
      "mit_id": "927891002",
      "kerberos_id": "erostova",
      "first_name": "Elena",
      "last_name": "Rostova",
      "email": "erostova@mit.edu",
      "phone": "+1 (617) 253-1005",
      "gender": "female",
      "cohort_year": "2022",
      "class_year": "Class of 2026",
      "current_year": 4,
      "current_semester": "semester_2",
      "academic_stage": "senior_graduation",
      "stage_label": "Phase 7: S.B. Conferral & Commencement Ready",
      "programme_id": "prog-mit-course18",
      "programme_name": "Course 18: Mathematics (Double Major Course 6-3)",
      "declared_major": "Course 18 Mathematics & Course 6-3 Computer Science",
      "departmental_advisor": "Prof. Gilbert Strang",
      "grading_policy": "regular",
      "cap_standing": "dean_list",
      "cap_status_label": "Summa Cum Laude / Degree Audit Cleared",
      "cumulative_gpa": 4.98,
      "term_rating": 5.0,
      "total_units_passed": 360,
      "total_credits_earned": 360,
      "pe_points_completed": 8,
      "swim_test_passed": true,
      "status": "graduated",
      "degree_awarded": "S.B. in Mathematics & S.B. in Computer Science and Engineering",
      "conferral_date": "2026-05-29",
      "diploma_status": "certified_conferred",
      "fees_status": "paid",
      "outstanding_balance": 0,
      "urop_active": false,
      "thesis_title": "Topological Data Analysis and High-Dimensional Spectral Embeddings"
    },
    {
      "id": "student-mit-06",
      "student_number": "928234819",
      "mit_id": "928234819",
      "kerberos_id": "joconnor",
      "first_name": "James",
      "last_name": "O'Connor",
      "email": "joconnor@mit.edu",
      "phone": "+1 (617) 253-1006",
      "gender": "male",
      "cohort_year": "2024",
      "class_year": "Class of 2028",
      "current_year": 2,
      "current_semester": "semester_2",
      "academic_stage": "cap_review",
      "stage_label": "Phase 5: CAP Academic Warning & Credit Cap (48u)",
      "programme_id": "prog-mit-course8",
      "programme_name": "Course 8: Physics",
      "declared_major": "Course 8: Physics",
      "departmental_advisor": "Prof. Robert Langer",
      "grading_policy": "regular",
      "cap_standing": "cap_warning",
      "cap_status_label": "CAP Academic Warning (Rating 2.82 / 5.0)",
      "cumulative_gpa": 2.82,
      "term_rating": 2.7,
      "total_units_passed": 120,
      "total_credits_earned": 120,
      "pe_points_completed": 4,
      "swim_test_passed": false,
      "status": "enrolled",
      "fees_status": "paid",
      "outstanding_balance": 0,
      "cap_petition": "Petition for 48-Unit Load Cap & Tutoring Plan Approved by CAP",
      "urop_active": false
    }
  ],
  "Enrollment": [
    {
      "id": "enr-p1",
      "student_id": "student-mit-01",
      "course_id": "crs-18-01",
      "course_code": "18.01",
      "term": "Fall 2026",
      "units": 12,
      "grade": "P",
      "grade_points": null,
      "result": "pass",
      "status": "completed",
      "coursework_score": 88,
      "exam_score": 92,
      "final_score": 90.4
    },
    {
      "id": "enr-p2",
      "student_id": "student-mit-01",
      "course_id": "crs-8-01",
      "course_code": "8.01",
      "term": "Fall 2026",
      "units": 12,
      "grade": "P",
      "grade_points": null,
      "result": "pass",
      "status": "completed",
      "coursework_score": 78,
      "exam_score": 84,
      "final_score": 81.6
    },
    {
      "id": "enr-p3",
      "student_id": "student-mit-01",
      "course_id": "crs-5-111",
      "course_code": "5.111",
      "term": "Fall 2026",
      "units": 12,
      "grade": "P",
      "grade_points": null,
      "result": "pass",
      "status": "completed",
      "coursework_score": 85,
      "exam_score": 89,
      "final_score": 87.4
    },
    {
      "id": "enr-p4",
      "student_id": "student-mit-01",
      "course_id": "crs-21w-755",
      "course_code": "21W.755",
      "term": "Fall 2026",
      "units": 12,
      "grade": "P",
      "grade_points": null,
      "result": "pass",
      "status": "completed",
      "coursework_score": 92,
      "exam_score": 95,
      "final_score": 92.9
    },
    {
      "id": "enr-m1",
      "student_id": "student-mit-02",
      "course_id": "crs-18-02",
      "course_code": "18.02",
      "term": "Spring 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 90,
      "exam_score": 94,
      "final_score": 92.4
    },
    {
      "id": "enr-m2",
      "student_id": "student-mit-02",
      "course_id": "crs-8-02",
      "course_code": "8.02",
      "term": "Spring 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 88,
      "exam_score": 91,
      "final_score": 89.8
    },
    {
      "id": "enr-m3",
      "student_id": "student-mit-02",
      "course_id": "crs-6-0001",
      "course_code": "6.0001",
      "term": "Spring 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 96,
      "exam_score": 98,
      "final_score": 97.0
    },
    {
      "id": "enr-m4",
      "student_id": "student-mit-02",
      "course_id": "crs-7-012",
      "course_code": "7.012",
      "term": "Spring 2026",
      "units": 12,
      "grade": "B",
      "grade_points": 4.0,
      "result": "pass",
      "status": "completed",
      "coursework_score": 74,
      "exam_score": 76,
      "final_score": 75.2
    },
    {
      "id": "enr-s1",
      "student_id": "student-mit-03",
      "course_id": "crs-6-006",
      "course_code": "6.006",
      "term": "Fall 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 95,
      "exam_score": 96,
      "final_score": 95.5
    },
    {
      "id": "enr-s2",
      "student_id": "student-mit-03",
      "course_id": "crs-6-004",
      "course_code": "6.004",
      "term": "Fall 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 94,
      "exam_score": 93,
      "final_score": 93.5
    },
    {
      "id": "enr-s3",
      "student_id": "student-mit-03",
      "course_id": "crs-18-03",
      "course_code": "18.03",
      "term": "Fall 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 91,
      "exam_score": 90,
      "final_score": 90.4
    },
    {
      "id": "enr-s4",
      "student_id": "student-mit-03",
      "course_id": "crs-14-01",
      "course_code": "14.01",
      "term": "Fall 2026",
      "units": 12,
      "grade": "B",
      "grade_points": 4.0,
      "result": "pass",
      "status": "completed",
      "coursework_score": 79,
      "exam_score": 81,
      "final_score": 80.2
    },
    {
      "id": "enr-e1",
      "student_id": "student-mit-05",
      "course_id": "crs-18-06",
      "course_code": "18.06",
      "term": "Fall 2025",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 98,
      "exam_score": 99,
      "final_score": 98.6
    },
    {
      "id": "enr-e2",
      "student_id": "student-mit-05",
      "course_id": "crs-6-033",
      "course_code": "6.033",
      "term": "Spring 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 96,
      "exam_score": 94,
      "final_score": 95.2
    },
    {
      "id": "enr-e3",
      "student_id": "student-mit-05",
      "course_id": "crs-6-115",
      "course_code": "6.115",
      "term": "Spring 2026",
      "units": 12,
      "grade": "A",
      "grade_points": 5.0,
      "result": "distinction",
      "status": "completed",
      "coursework_score": 97,
      "exam_score": 98,
      "final_score": 97.2
    },
    {
      "id": "enr-j1",
      "student_id": "student-mit-06",
      "course_id": "crs-8-02",
      "course_code": "8.02",
      "term": "Spring 2026",
      "units": 12,
      "grade": "D",
      "grade_points": 2.0,
      "result": "pass",
      "status": "completed",
      "coursework_score": 48,
      "exam_score": 46,
      "final_score": 46.8
    },
    {
      "id": "enr-j2",
      "student_id": "student-mit-06",
      "course_id": "crs-18-03",
      "course_code": "18.03",
      "term": "Spring 2026",
      "units": 12,
      "grade": "C",
      "grade_points": 3.0,
      "result": "pass",
      "status": "completed",
      "coursework_score": 56,
      "exam_score": 54,
      "final_score": 54.8
    }
  ],
  "UROPProject": [
    {
      "id": "urop-1",
      "student_id": "student-mit-03",
      "student_name": "Sophia Kowalski",
      "title": "Zero-Knowledge Cryptographic SNARKs for Decentralized Ledgers",
      "faculty_supervisor": "Prof. Shafi Goldwasser",
      "lab": "CSAIL (Computer Science and Artificial Intelligence Laboratory)",
      "department": "EECS",
      "type": "Direct Funding ($2,100 / term)",
      "status": "active",
      "term": "Fall 2026 - Spring 2027",
      "proposal_abstract": "Investigation of succinct non-interactive arguments of knowledge with sublinear verification time on high-throughput distributed transaction ledgers."
    },
    {
      "id": "urop-2",
      "student_id": "student-mit-02",
      "student_name": "Marcus Vance",
      "title": "Distributed Byzantine Fault Tolerance at CSAIL",
      "faculty_supervisor": "Prof. Tim Berners-Lee",
      "lab": "CSAIL Decentralized Information Group",
      "department": "EECS",
      "type": "Academic Credit (12 Units)",
      "status": "approved",
      "term": "Spring 2026",
      "proposal_abstract": "Benchmarking asynchronous consensus protocols under adversarial network partitioning."
    },
    {
      "id": "urop-3",
      "student_id": "student-mit-04",
      "student_name": "David Kim",
      "title": "Biomimetic Soft Actuators at MIT Media Lab",
      "faculty_supervisor": "Prof. Robert Langer",
      "lab": "Media Lab Tangible Media Group",
      "department": "Mechanical Engineering / Media Lab",
      "type": "Direct Funding ($2,100 / term)",
      "status": "active",
      "term": "Spring 2026",
      "proposal_abstract": "Development of electro-pneumatic soft robotic grippers using biocompatible hydrogel membranes."
    }
  ],
  "AcademicAdvisor": [
    {
      "id": "adv-1",
      "name": "Prof. Gerald Sussman",
      "title": "Panasonic Professor of Electrical Engineering",
      "department": "EECS",
      "role": "UAC First-Year Advisor & Faculty",
      "email": "gjs@mit.edu",
      "office": "32-G492"
    },
    {
      "id": "adv-2",
      "name": "Prof. Shafi Goldwasser",
      "title": "RSA Professor of Computer Science",
      "department": "EECS",
      "role": "Course 6 Major Faculty Advisor",
      "email": "shafi@theory.csail.mit.edu",
      "office": "32-G682"
    },
    {
      "id": "adv-3",
      "name": "Prof. Gilbert Strang",
      "title": "Professor of Mathematics",
      "department": "Mathematics",
      "role": "Course 18 Major Advisor",
      "email": "gilstrang@math.mit.edu",
      "office": "2-240"
    },
    {
      "id": "adv-4",
      "name": "Prof. Robert Langer",
      "title": "Institute Professor",
      "department": "Biological & Chemical Engineering",
      "role": "UROP Research Mentor & Advisor",
      "email": "rlanger@mit.edu",
      "office": "76-661"
    },
    {
      "id": "adv-5",
      "name": "Prof. Sherry Turkle",
      "title": "Abby Rockefeller Mauz\u00e9 Professor",
      "department": "STS / HASS",
      "role": "HASS Concentration Advisor",
      "email": "sturkle@mit.edu",
      "office": "E51-296"
    }
  ]
};

export default MIT_SAMPLE_DATA;
